<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="192.168.1.4" ignored="0" name="Surefire test" tests="3" failures="1" timestamp="2020-03-30T01:25:37 IST" time="45.243" errors="0">
  <testcase name="login" time="30.705" classname="urllogin.LoginTest"/>
  <testcase name="loginfail" time="11.268" classname="urllogin.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [Home | Let&amp;apos;s Kode It] but found [Let&amp;apos;s Kode It]">
      <![CDATA[java.lang.AssertionError: expected [Home | Let's Kode It] but found [Let's Kode It]
at urllogin.LoginTest.loginfail(LoginTest.java:41)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- loginfail -->
  <testcase name="shouldAnswerWithTrue" time="0.002" classname="jenkins.selenium_testng_jenkins.AppTest"/>
</testsuite> <!-- Surefire test -->
